import Head from 'next/head';
import { Product, HeroBanner, FooterBanner } from '../components';

export default function Home() {
   return (
      <div>
         <Head>
            <title>E-Comerce</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <>
            <HeroBanner />

            <div className='text-center my-10'>
               <h2 className='text-4xl font-bold text-sky-900'>Best Selling Products</h2>
               <p className='text-base text-gray-400'>Speakers of many variations</p>
            </div>

            <div className='flex flex-wrap justify-center gap-4 mt-5 w-full'>
               {['Product 1', 'Product 2'].map((product) => product)}
            </div>

            <FooterBanner /> 
         </>

      </div>
   )
}
