import Head from 'next/head';
import { Product, HeroBanner, FooterBanner } from '../components';
import apolloClient from '../lib/graphql/apolloClient';
import { GET_POSTS, GET_BANNERS } from '../lib/graphql/graphcms/queries';

export default function Home({ products, banners }) {
   // console.log('productsData', products);
   // console.log('bannersData', banners);
   return (
      <div>
         <Head>
            <title>E-Comerce</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
         </Head>

         <>
            <HeroBanner />

            <div className='text-center my-10'>
               <h2 className='text-4xl font-bold text-sky-900'>Best Selling Products</h2>
               <p className='text-base text-gray-400'>Speakers of many variations</p>
            </div>

            <div className='flex flex-wrap justify-center gap-4 mt-5 w-full'>
               {products.map((product) => product.name)}
            </div>

            <FooterBanner />
         </>

      </div>
   )
}

export const getServerSideProps = async () => {

   const res_products = await apolloClient.query({ query: GET_POSTS });
   const products = res_products.data.products;

   const res_banners = await apolloClient.query({ query: GET_BANNERS });
   const banners = res_banners.data.banners;
   return {
      props: {
         products,
         banners
      }
   }
}